[Feature] Header Component 구현
limdumb/DodGe.gg pull request #14
Opened 2022-11-23 07:12 UTC by limdumb

**내가 구현한 기능들**
* Header Component
* 검색 Input
* Submit Button
- - -
**하면서 어려웠던 점**
* 반응형 단위에 대한 정리
* 미디어쿼리
- - -
**궁금한 점(없으면안써도 괜찮음)**
* 반응형 웹에 대한.. 전체적인 로직이 궁금함

2022-11-23 08:52 UTC, shim5505 commented
경인님 코드 잘 리뷰했습니다.
전체적으로 잘 짜신 것 같아 역시 든든합니다.
기능 구현도 잘 된 것 같은데, 아직 제가 깃이 미숙해서 확인이 어렵네요 ㅠ 그래서 코드 자체만 보고 판단 드리는 부분이라 잘못 이해하고 있는 부분이 있습니다. 이 부분 양해 부탁드립니다🙏🏻

-------

- 스타일 컴포넌트 관련

TabButton , SubmitButton 같은 경우 재활용성이 없다면 (Header 자체로 재활용한다면) MainHeader의 return문 안에는 컴포넌트만 보이는 것이 가독성을 높일 수 있을 것 같아요!

2022-11-23 09:00 UTC, shim5505 reviewed
경인님 코드 잘 리뷰했습니다.
전체적으로 잘 짜신 것 같아 역시 든든합니다.
기능 구현도 잘 된 것 같은데, 아직 제가 깃이 미숙해서 확인이 어렵네요 ㅠ 그래서 코드 자체만 보고 판단 드리는 부분이라 잘못 이해하고 있는 부분이 있습니다. 이 부분 양해 부탁드립니다🙏🏻

2022-11-23 09:00 UTC, shim5505 commented on src/App.css
> +}
414 412 픽셀처럼 차이가 적은 경우의 미세한 폰트 사이즈 조정이 필요할까요?

2022-11-23 09:00 UTC, shim5505 commented on src/Components/Header.jsx
> +        <SubmitButton
TabButton , SubmitButton 같은 경우 재활용성이 없다면 (Header 자체로 재활용한다면) MainHeader의 return문 안에는 컴포넌트만 보이는 것이 가독성을 높일 수 있을 것 같아요!

2022-11-23 09:12 UTC, limdumb commented on src/App.css
> +}
넵 만약 미세한 조정이 필요하다면 :0 조정해도 될꺼같습니다

2022-11-23 09:17 UTC, limdumb commented on src/Components/Header.jsx
> +        <SubmitButton
두개의 버튼은 공통되는 속성들이 있어서 중복되는 코드를 쓰고싶지 않아서 Styled Button이라는 컴포넌트를 하나 만들었고 SubmitButton과 TabButton을 만들어서 상속 받은 후에 따로 스타일링을 진행한 컴포넌트 입니다 :)
- - -
동일한 코드가 나오는 것도 결과적으론 가독성 적으로 보면 좋지 않을수 있을것 같아서 상속하는 방법을 택했습니다!
그리고 StyledButton같은 경우는 기본적인 props를 정의 해둔 컴포넌트이다 보니 재사용성 측면도 좋을것 같아서
해당 코드처럼 상속을 받을수 있는 컴포넌트를 만들었습니다 !

2022-11-23 11:45 UTC, rlawodn46465 requested changes
경인님 고생 많으셨어요!
확실히 코드만 보고 파악하기 힘들긴 하네요
저는 퍼블리싱쪽으로 조금만 글을 남길게요!

2022-11-23 11:45 UTC, rlawodn46465 commented on src/Components/Header.jsx
> +`;
이 부분에서 가로 스크롤이 생길거 같아요! 그래서 
`box-sizing: border-box`
를 추가하면 가로 스크롤이 사라질거 같아요!

2022-11-23 11:45 UTC, rlawodn46465 commented on src/Components/Header.jsx
> +        </SubmitButton>
div로 input태그랑 Submitbutton을 묶기 보다는 Submitbutton 안에 input 태그랑 span 태그를 추가해 span태그에 .GG를 넣어 위치를 조정하면 조금 더 깔끔할거 같아요!
`<SubmitButton>
  <input/>
  <span>.GG</span>
</SubmitButton>
`
그 이후 SubmitButton에 position: relative를 주시고 span에 position: absolute;를 주셔서 위치이동 시키고 z-index로 .GG를 위쪽으로 뛰우면 될거 같아요

2022-11-24 08:25 UTC, limdumb commented on src/Components/Header.jsx
> +`;
해당 부분은 position은 아에 빼버리고 새로운 형식으로 변경 했습니다 :) 확인부탁드려요

2022-11-24 08:25 UTC, limdumb commented on src/Components/Header.jsx
> +        </SubmitButton>
말씀하신 부분으로 고쳤습니다 ! :)

2022-11-24 08:25 UTC, limdumb commented on src/Components/Header.jsx
> +`;
반영 완료했습니다

2022-11-24 08:26 UTC, rlawodn46465 approved these changes

2022-11-24 08:26 UTC, merged