[Feat] Footer 컴포넌트 구현
limdumb/DodGe.gg pull request #16
Opened 2022-11-23 08:07 UTC by shim5505

내가 구현한 기능들
* 전체 구조 정리 및 컴포넌트화 진행 
* 간단한 CSS 스타일링
- - -
하면서 어려웠던 점
* EmailJS 시도...쉽지 않다
- - -
궁금한 점(없으면안써도 괜찮음)
* 이메일 쓰나요? 아니면 아예 삭제? 관련해서 이야기 해봤으면 좋겠습니다
* 이 외 추가할 기능이 솔직히 생각나지 않았습니다. 코멘트로 알려주세요

2022-11-23 08:55 UTC, limdumb approved these changes
안녕하세요 민섭님 :0 코드 잘 봤습니다 !!
역시.. 코딩능력자셔서 그런지 전체적으로 유지보수성이나 깔끔한 코드를 짜신것 같습니다 :)
특별하게 기능이 존재하는 컴포넌트가 아니여서 어찌보면 대충 만들수도 있는데
파일로 컴포넌트화 시켜서 유지보수성도 신경쓰신것 같아서 든든합니다..!!
수고 너무 많으셨어요 :)

2022-11-23 08:55 UTC, limdumb commented on src/Components/Footer.jsx
> +        />
컴포넌트에 Props로 받아서 사용했군요..! 유지 보수성이 좋을것 같습니다 :)

2022-11-23 08:55 UTC, limdumb commented on src/Components/Footer.css
> +}
반응형 구현이 되어있을까요?.? 궁금합니다!

2022-11-23 12:21 UTC, rlawodn46465 requested changes
민섭님 푸터 부분 코드 확인했습니다!
아까 이메일 작업하는거 엎은게 많이 아쉽네요 ㅠ
전체적으로 코드 잘 구성되어 있지만 밑에 남기는 부분에 대해 조금 읽어봐주셔요!
고생 많으셨습니다!!

2022-11-23 12:21 UTC, rlawodn46465 commented on src/Components/Footer.jsx
> +        <p>© 2022 DodGe.gg</p>
엄..이거 div가 안닫힌거 같은데 맞나요? footer 태그도 닫는 태그가 안보여요

2022-11-23 12:21 UTC, rlawodn46465 commented on src/Components/Footer.jsx
> +          git={"https://github.com/rlawodn46465"}
해당 부분의 이름과 ,git, blog, email을 객체 state로 관리해서 map으로 컴포넌트를 반복시키면 좋을거 같아요!
```
const [변수명,set변수명] = useState([
{
name: 이름,
git: 깃 주소,
blog: 블로그 주소,
email: 이메일 주소
}, {}, {}, {}
])

{
변수명.map( data => {
return  <Member  data={data}/>
})
}
```

2022-11-23 14:52 UTC, shim5505 commented on src/Components/Footer.css
> +}
Footer다 보니 반응형이 크게 중요치 않다고 생각했는데, 생각해보니 폰트 사이즈에 따른 리사이징이 필요하겠네요. 수정하겠습니다 👍🏻

2022-11-23 14:54 UTC, shim5505 commented on src/Components/Footer.jsx
> +        <p>© 2022 DodGe.gg</p>
단순 오류 같습니다! 밑에 코드 보시면 잘 닫혀 있습니다 🙂

2022-11-23 14:57 UTC, shim5505 commented on src/Components/Footer.jsx
> +          git={"https://github.com/rlawodn46465"}
해당 데이터같은 경우 따로 상태 관리에 따른 보존성이 크게 중요하지 않을 것 같아서 생략했습니다. 상태 변수가 재활용성이 없을 때 코드에 웹 페이지 기능성에 영향을 주는지 확인해보고, 문제 없다면 가독성을 위해 수정하겠습니다. 피드백 감사합니다 🙂

2022-11-24 08:04 UTC, shim5505 commented on src/Components/Footer.jsx
> +          git={"https://github.com/rlawodn46465"}
관련해서 진행해 보았는데, 데이터 변동성이 적고 직관성 관점에서 현재 코드가 괜찮은 거 같아서 그대로 진행하겠습니다! 데이터 핸들링 측면에서는 매우 좋은 아이디어라 이후 상태값을 필요로 하는 경우 고려해서 작성하겠습니다 🙂

2022-11-24 08:25 UTC, rlawodn46465 approved these changes

2022-11-24 08:25 UTC, merged