[Refact] Header Refactoring
limdumb/DodGe.gg pull request #24
Opened 2022-12-03 04:28 UTC by limdumb

**내가 구현한 기능들**
* search input 리팩토링 ( Button 안에 Input이 있으면 안된다고함 )
* 헤더 컴포넌트 분리
* 인풋 미디어 쿼리 적용
- - -
**하면서 어려웠던 점**
* 미디어쿼리

2022-12-03 12:41 UTC, rlawodn46465 requested changes
경인님 리팩토링 고생 많으셨습니다! 
전체적으로 코드 경량화가 된거 같아 보여 멋집니다~!
직접 실행할 수 없고 코드만 보는거에 한계가 있어 리뷰 하나를 남겨뒀습니다!

2022-12-03 12:41 UTC, rlawodn46465 commented on src/Components/CommonComponents/Header.jsx
>    float: left;
혹시 float를 사용하신 이유가 있으신가요?
header라서 float를 사용 안해도 괜찮을거 같아서요

2022-12-04 14:11 UTC, limdumb commented on src/Components/CommonComponents/Header.jsx
>    float: left;
해당부분은 전체적인 레이아웃 리팩토링 할때 삭제 하였습니다 :) 아직 PR이 올라가기 전 상태라서 아마 곧 올라갈꺼에요!

2022-12-04 15:14 UTC, rlawodn46465 approved these changes

2022-12-04 15:37 UTC, merged