[Feat] 챔피언가이드 컴포넌트 기능
limdumb/DodGe.gg pull request #29
Opened 2022-12-09 13:58 UTC by shim5505

**Task Done**
1. 더미 데이터를 기반으로 전체 컴포넌트 내용 변경
- Riot API를 기반으로 한 데이터와 더미 데이터를 사용해 챔피언 이름에 따라 모든 정보 업데이트
- 기존의 소환사 주문 및 시작 아이템 추천 데이터 삭제 => 모바일에서 카운터 리스트가 보이게 대체
- 이름에 따라 알맞는 신발/시작아이템을 추천하는 자체 메서드 생성 (QuickBuild.jsx)
- 더미 데이터에 따라 선택된 룬 및 파편이 강조
2. 디자인 개선
- 기존에 디자인 화면이 어긋나는 부분을 수정 => 현재 모바일만 지원

**TODO:**
1. 모든 더미 데이터 생성 이후 모든 정보가 알맞게 들어가는지 테스트
2. 디자인 이상 확인 및 문제 없을 시 이후 태블릿/PC에 맞는 디자인 구현
3. (시간이 난다면) 스킬 정보 및 아이템 정보 등 표시?

**어려웠던 점**
1. 전체 데이터 일관성 유지 
2. 일부 디자인 오류
3. 늘어지는 코드로 떨어지는 가독성

2022-12-09 14:27 UTC, limdumb requested changes
민섭님 안녕하세요 :) 오늘 코드도 고생 너무 많으셨어요
이번주는 데이터에 관련된 이야기로 저희가 많이 의논했던것 같은데
데이터의 정리가 잘된 모습들이 보기좋습니다 :)
이번 리뷰는 조금 아쉬웠던 부분들을 코멘트로 달아드렸습니다!
리뷰는 주관적으로 의견을 제시 하는것이지 강요가 아니라는점 다시한번 말씀 드리고!
고생 너무 많으셨습니다 :)

2022-12-09 14:27 UTC, limdumb commented on src/Components/ChampionGuide/CountersList.jsx
> +import DetailedData from "./Data/DetailedData.json";
DetaileData 라는 변수명은 유추하기가 어려운것 같아요 :) 다른 변수명으로 변경해보는게 좋을듯 합니다

2022-12-09 14:27 UTC, limdumb commented on src/Components/ChampionGuide/CountersList.jsx
> +        <CounterItem currentChamp={currentChamp} idx={4} />
CounterItem 보다는 CounterChampion이 조금더 직관적인 변수명이 될듯 싶습니다 :)

2022-12-09 14:27 UTC, limdumb commented on src/Components/ChampionGuide/CountersList.jsx
> +  const ImagesURL = "http://ddragon.leagueoflegends.com/cdn/12.21.1/img";
어떤 Image의 URL인지 적어주면 더 좋을것 같습니다!

2022-12-09 14:27 UTC, limdumb commented on src/Components/ChampionGuide/CountersList.jsx
> +      <div className="Flex_Wrapper">
Flex_Wrapper라는 친구가 반복적으로 나오고 있습니다! 클래스명이 어떤걸 의미하는지 유추하기 어렵기도 해요ㅠㅠ!
그리고 반복적으로 재사용 되어야 하는친구라면 Styled Component로 묶어보는게 좋을것 같습니다 :)

2022-12-09 14:34 UTC, rlawodn46465 requested changes
이번 챔피언 가이드 고생 많으셨습니다!
이번 프로젝트의 핵심중 하나를 멋지게 만드셨네요!!
이번 코드를 지속적으로 수정해서 그런지 이상한 부분이 별로 없네요
저는 딱 하나만 수정했으면 하는 마음에 리뷰 하나 달았습니다!

2022-12-09 14:34 UTC, rlawodn46465 commented on src/Components/ChampionGuide/CountersList.jsx
> +function CounterItem(props) {
props말고 { currentChamp, idx} 이렇게 받아오는게 아래 값 할당할때 더 깔끔할거 같아요!

2022-12-09 14:45 UTC, shim5505 commented on src/Components/ChampionGuide/CountersList.jsx
> +import DetailedData from "./Data/DetailedData.json";
동의합니다. 관련해서 현재 받아오고 있는 더미데이터가 추가적인 "통계"자료임을 고려해 ChampionStatistics.json으로 교체하겠습니다

2022-12-09 14:49 UTC, shim5505 commented on src/Components/ChampionGuide/CountersList.jsx
> +        <CounterItem currentChamp={currentChamp} idx={4} />
좋은 지적 감사합니다. ListItem과 혼동해서 사용하고 있었네요 💦

2022-12-09 14:52 UTC, shim5505 commented on src/Components/ChampionGuide/CountersList.jsx
> +  const ImagesURL = "http://ddragon.leagueoflegends.com/cdn/12.21.1/img";
해당 이름은 코드 효율을 위해 item, champion, spell 등 모든 png 이미지의 링크를 통과할 때 사용하는 기본 URL로 사용하고 있습니다.

좀 더 좋은 이해를 위해 변수명을 BaseURL로 수정하도록하겠습니다.

2022-12-09 14:56 UTC, shim5505 commented on src/Components/ChampionGuide/CountersList.jsx
> +      <div className="Flex_Wrapper">
헛 죄송합니다 🙇🏻‍♂️ 해당 div의 경우 각각의 ListItem의 flex 속성을 통해 같은 간격으로 보여주기 위해 사용하고 있습니다.

Styled Component를 통해 좀 더 획일화된 이름을 부여하도록 하겠습니다

2022-12-09 15:09 UTC, shim5505 commented on src/Components/ChampionGuide/CountersList.jsx
> +function CounterItem(props) {
좋은 지적 감사합니다. 관련해서 props로 전달받는 컴포넌트는 구조 분해 할당을 통해 값을 더 명시적으로 표시하도록 하겠습니다.

2022-12-10 03:13 UTC, limdumb commented on src/Components/ChampionGuide/CountersList.jsx
> +  const ImagesURL = "http://ddragon.leagueoflegends.com/cdn/12.21.1/img";
그렇군요! 그렇다면 그냥 BaseURL보다는 ChampInfoURL은 어떨까요? 조금 더 직관적인 느낌일꺼 같아요

2022-12-11 09:32 UTC, rlawodn46465 approved these changes

2022-12-11 11:09 UTC, merged