Design/op list
limdumb/DodGe.gg pull request #42
Opened 2022-12-15 14:28 UTC by rlawodn46465

내가 구현한 기능들
* OPList 디자인 적용
* 
* 
- - -
하면서 어려웠던 점
* 디자인 적용...
* 
* 
- - -
궁금한 점(없으면안써도 괜찮음)
* 
* 
*

2022-12-16 15:30 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

거의 500줄에 육박한 코드라니...엄청난 노력과 정성이 들어간 PR이네요.
전체적으로 너무 잘 작성하신 코드고, 디자인적으로 많이 고려해서 반응형 웹에 맞춰 작성하신게 느껴집니다.
일부 주석 처리가 되어있는 코드가 필요한 부분인지 아닌지 몰라서 우선은 코멘트를 달아놓았습니다. 해당 부분이 필요없다면 삭제해주시면 될 것 같고, 아니시라면 머지 이후 과정을 위해 남겨놓으시면 될 것 같습니다.

고생 많으셨습니다!!

2022-12-16 15:30 UTC, shim5505 commented on src/Components/Nav/Nav.css
> +  background-image: 1;
background-image 속성에서 1을 줬을 때 어떤 기능을 하나요?

2022-12-16 15:30 UTC, shim5505 commented on src/Components/Nav/Nav.jsx
> +  }
겹치는 CSS가 많은 것 같은데 props때문에 나눠 놓으신 것 같네요. NavButton 클래스와 top1, top2, top3 클래스로 나누어 겹치는 부분의 코드를 따로 분리하는 것은 어떨까요?
그렇다면 className="NavButton top1" 또는 className="NavButton top2" 등이 될 수 있을 것 같아요

2022-12-16 15:30 UTC, shim5505 commented on src/Components/Nav/Nav.jsx
> +// `;
주석 처리가 되어있는데 필요한 코드인가요?

2022-12-16 15:30 UTC, shim5505 commented on src/Components/Nav/Nav.jsx
>          <NavEffect clickCheck={clickCheck} className="quadrant4" />
이 부분도 주석이 섞여있는데, 필요하다면 어떤 용도인지 주석 앞에 적어놓아 주시는게 좋을 것 같습니다 🙂

2022-12-16 15:30 UTC, shim5505 commented on src/Components/OPList/ChampionsList.css
> +}
비어있는 미디어쿼리는 추가 작성하기 위해 남겨놓으신걸까요? 만약 현재 디자인이 반응형 웹에 맞게 잘 적용된다면 해당 부분은 삭제해도 될 것 같습니다!

2022-12-16 15:30 UTC, shim5505 commented on src/Components/TapComponent/Tab.css
> +  /* width: 100%; */
해당 주석은 삭제해도 될 것 같습니다.

2022-12-16 15:30 UTC, shim5505 commented on src/Components/TapComponent/Tab.css
> +  height: calc(10 * 4.8496px);
48.496px 또는 48~50px이 아닌 calc를 쓰신 이유가 있으실까요?

2022-12-16 15:30 UTC, shim5505 commented on src/Components/TapComponent/Tab.css
>  }
미세한 차이가 있어서 나눠 놓으신거군요. 정성 가득한 CSS네요. 감동했습니다👏

2022-12-17 05:35 UTC, rlawodn46465 commented on src/Components/Nav/Nav.jsx
> +  }
해당 코드는 겹쳐서 보여주는 코드라 완전히 합치기는 그렇지만 말씀대로 클래스 하나 더 만들어서 줄일 수 있을거 같아요!  수정하겠습니다!

2022-12-17 05:39 UTC, rlawodn46465 commented on src/Components/Nav/Nav.css
> +  background-image: 1;
background-image에 숫자 1을 넣는 이유는 정확하게 모르겠어요...
저렇게 준 이유가 border에 그라데이션 효과를 넣기 위해 그대로 따라한 방식이라서요. 나중에 확인되면 알려 드리겠습니다!

2022-12-17 05:43 UTC, rlawodn46465 commented on src/Components/TapComponent/Tab.css
> +  height: calc(10 * 4.8496px);
육각형을 나타내기 위한 수식입니다! width값과 저 4.8496이라는 숫자가 비율이 맞아야 육각형 모양이 나옵니다!
ex) width: 56px; height: calc(10 * 9.6992px);

2022-12-17 05:43 UTC, rlawodn46465 commented on src/Components/TapComponent/Tab.css
>  }
흑흑...감사합니다!

2022-12-17 05:44 UTC, rlawodn46465 commented on src/Components/TapComponent/Tab.css
> +  /* width: 100%; */
필요없는 주석들은 싹 지우겠습니다!

2022-12-17 05:44 UTC, rlawodn46465 commented on src/Components/Nav/Nav.jsx
>          <NavEffect clickCheck={clickCheck} className="quadrant4" />
필요없는 주석들은 싹 지우겠습니다!

2022-12-17 05:44 UTC, rlawodn46465 commented on src/Components/Nav/Nav.jsx
> +// `;
필요없는 주석들은 싹 지우겠습니다!

2022-12-17 05:45 UTC, rlawodn46465 commented on src/Components/OPList/ChampionsList.css
> +}
해당 부분은 추후 챔피언리스트와 합쳐야하는 부분이라 남겨뒀습니다!

2022-12-17 11:19 UTC, shim5505 approved these changes

2022-12-19 04:12 UTC, merged

2022-12-19 04:13 UTC, limdumb commented
건강 이슈로 재우 리뷰만 진행 후 머지