[Style] Header 구현
limdumb/DodGe.gg pull request #44
Opened 2022-12-22 00:51 UTC by limdumb

**내가 구현한 기능들**
* 다크모드 헤더 구현
* 기본 헤더 스타일 구현
* 챔피언 리스트의 일정부분도 구현함
- - -
**하면서 어려웠던 점**
* 일러스트레이터..
* 디자인 포지션에 대한 부분

2022-12-25 15:13 UTC, rlawodn46465 approved these changes
고생 많으셨습니다 경인님!
지금 하고 있는 프리 프로젝트 때문에 못하고 있다는 핑계가 부끄러울 정도입니다 ㅠㅠ..
이미 다 작성한 코드에서 디자인을 입힌다는게 많이 힘든데 대단합니다!
이번 PR에서는 하나의 의견만 있습니다!

2022-12-25 15:13 UTC, rlawodn46465 commented on src/Components/CommonComponents/SearchInput.jsx
> +      ></input>
태그 내부에 값을 넣지 않는 태그는 바로 닫는 태그를 사용하는게 좋을거 같아요! <input></input>은 <input/> 이렇게요

2022-12-26 08:56 UTC, shim5505 requested changes
경인님 코드 잘 봤습니다.

방대한 양인데도 코드를 잘 구성하셔서 수정에 대한 제안보다는 궁금한 점 위주로 물어보게 되네요. 확인 한 번만 해주시고 답변 달아주시면 감사하겠습니다. 

코드 리뷰가 늦은 점 죄송합니다 💦
고생 많으셨습니다!

2022-12-26 08:56 UTC, shim5505 commented on src/Components/ChampList/ChampionList.css
>  }
768px ~ 1023px (태블릿 사이즈)를 위한 디자인이 필요한가요? 필요없다면 해당 부분은 삭제해도 될 것 같습니다.

2022-12-26 08:56 UTC, shim5505 commented on src/Components/ChampList/ChampionList.jsx
> +                  </div>
다크모드에 맞게 설정해두신 부분이군요. 고생 많으셨습니다 👍🏻

2022-12-26 08:56 UTC, shim5505 commented on src/Components/CommonComponents/Header.css
> +  background: linear-gradient(90deg, rgba(180,90,36,0.97) 2.991%, rgba(251,176,59,0.5) 51.3966%, rgba(180,90,36,1) 100%);
해당 그라데이션은 질감 표현을 위한 건가요?

2022-12-26 08:56 UTC, shim5505 commented on src/Components/CommonComponents/Header.jsx
> +//FF00FF
필요하신 주석이 아니라면 삭제하셔도 될 것 같습니다.

2022-12-26 11:01 UTC, limdumb commented on src/Components/ChampList/ChampionList.css
>  }
해당부분은 챔피언리스트 브랜치로 다시 만들어서 한번더 작업할 예정입니다 :)

2022-12-26 11:01 UTC, limdumb commented on src/Components/CommonComponents/Header.css
> +  background: linear-gradient(90deg, rgba(180,90,36,0.97) 2.991%, rgba(251,176,59,0.5) 51.3966%, rgba(180,90,36,1) 100%);
디자인 시안에서 그라데이션이 들어가서 만들어봤습니다 !

2022-12-26 16:40 UTC, shim5505 approved these changes

2022-12-28 00:19 UTC, merged